# Generated by Django 4.2.6 on 2024-04-21 18:45

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDiabetesScreeningData',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('pregnancies', models.IntegerField(help_text='Number of times pregnant.', validators=[django.core.validators.MinValueValidator(0)])),
                ('glucose', models.IntegerField(help_text='Plasma glucose concentration over 2 hours in an oral glucose tolerance test.', validators=[django.core.validators.MinValueValidator(0)])),
                ('blood_pressure', models.IntegerField(help_text='Diastolic blood pressure (mm Hg).', validators=[django.core.validators.MinValueValidator(0)])),
                ('skin_thickness', models.IntegerField(help_text='Triceps skinfold thickness (mm).', validators=[django.core.validators.MinValueValidator(0)])),
                ('insulin', models.IntegerField(help_text='2-Hour serum insulin (mu U/ml).', validators=[django.core.validators.MinValueValidator(0)])),
                ('bmi', models.FloatField(help_text='Body mass index (weight in kg / height in m^2).', validators=[django.core.validators.MinValueValidator(0)])),
                ('diabetes_pedigree_function', models.FloatField(help_text='Diabetes pedigree function, a genetic score of diabetes.', validators=[django.core.validators.MinValueValidator(0)])),
                ('age', models.IntegerField(help_text='Age of the individual.', validators=[django.core.validators.MinValueValidator(0)])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Associated User')),
            ],
            options={
                'verbose_name': 'User Diabetes Screening Data',
                'verbose_name_plural': "Users' Diabetes Screening Data",
            },
        ),
    ]
