# Generated by Django 4.2.6 on 2024-04-24 21:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdiabetesscreeningdata',
            name='DOB',
            field=models.DateField(default=datetime.datetime.now, help_text='Date of birth of the individual.'),
        ),
        migrations.AddField(
            model_name='userdiabetesscreeningdata',
            name='name',
            field=models.CharField(default='', help_text='Name of the individual.', max_length=255),
        ),
    ]
